version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - exchange
    # volumes: 
    #   - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - exchange
    volumes: 
      - redis:/data

networks:
  exchange:
    name: exchange-network

volumes:
  mongo:
    driver: local
  # rabbitmq:
  #   driver: local
  redis:
    driver: local